### ISSUE TITLE
Find a reasonable pricing web hosting service

### ISSUE THREAD

**Issue by yukiyohure** [genesis-tech-tribe/nishiki-frontend#21]
## Overview
Hosting a repository of GitHub Organization require a Vercel's Team, which costs 20USD/mo. It would be better if there are any other web app hosting services with lower pricing.

## Criterias
- Find other web app hosting services (e.g. Netlify, AWS Amplify)
- Enable preview deployment for each GitHub Pull Request (Important for PR reviews!)

## Additional Context
- https://discord.com/channels/1154534169796431873/1159594355301023764

**Comment by uskayyyyy** [comment]
```[tasklist]
### Tasks
- [ ] Draft task
```

**Comment by uskayyyyy** [comment]
Decided to host the app using AWS Amplify.

**Comment by uskayyyyy** [comment]
## Tasks
- [ ] Update package.json and apply it to the `develop` and `main` branches.
- [ ] Set up the Amplify web app hosting for this repository, targeting the `develop` and `main` branches.
- [ ] Set up PR previews for `develop` and `main` branches.

**Comment by uskayyyyy** [comment]
Once ensuring a PR preview is triggered, this issue can be closed.

**Comment by uskayyyyy** [comment]
Though we have earlier decided to use the "AWS Amplify Web Hosting" service, we settled to not use any web hosting services because we recently updated to the latest Next.js v14, which is not supported by AWS Amplify for now although v13 is supported.

Reference: https://aws.amazon.com/blogs/mobile/amplify-next-js-13/
There was not even a single page that mentioned about Next.js 14
